name = "portfolio-kevin"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "portfolio-kevin"
route = "kevinmickael.com/*"
zone_id = "REMPLACER_PAR_TON_ZONE_ID"

[env.production.vars]
NODE_ENV = "production"

[env.production.rules]
type = "ESModule"
globs = ["**/*.js", "**/*.ts", "**/*.tsx"]

# Configuration pour les pages statiques
[env.production.pages]
bucket = ".next/static"
entry-point = "workers-site"

# Headers de sécurité et performance
[[env.production.headers]]
for = "/*"
[env.production.headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache pour les images
[[env.production.headers]]
for = "/images/*"
[env.production.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les assets statiques
[[env.production.headers]]
for = "/_next/static/*"
[env.production.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les fonts
[[env.production.headers]]
for = "/fonts/*"
[env.production.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Compression
[env.production.compression]
gzip = true
brotli = true

# Optimisations de performance
[env.production.optimization]
minify = true
bundle = true 