name: Notify IndexNow after Deploy

on:
  push:
    branches: [main]

jobs:
  notify-indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Notify IndexNow
        run: |
          curl -X GET "https://creativfolio.com/api/indexnow" 